config/routes.rb
Rails.application.routes.draw do
  resources :frontpages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  #
  root "frontpages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/frontpage.rb
class Frontpage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/frontpages_controller.rb
class FrontpagesController < ApplicationController
  before_action :set_frontpage, only: [:show, :edit, :update, :destroy]

  # GET /frontpages
  # GET /frontpages.json
  def index
    @frontpages = Frontpage.all
  end

  # GET /frontpages/1
  # GET /frontpages/1.json
  def show
  end

  # GET /frontpages/new
  def new
    @frontpage = Frontpage.new
  end

  # GET /frontpages/1/edit
  def edit
  end

  # POST /frontpages
  # POST /frontpages.json
  def create
    @frontpage = Frontpage.new(frontpage_params)

    respond_to do |format|
      if @frontpage.save
        format.html { redirect_to @frontpage, notice: 'Frontpage was successfully created.' }
        format.json { render :show, status: :created, location: @frontpage }
      else
        format.html { render :new }
        format.json { render json: @frontpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frontpages/1
  # PATCH/PUT /frontpages/1.json
  def update
    respond_to do |format|
      if @frontpage.update(frontpage_params)
        format.html { redirect_to @frontpage, notice: 'Frontpage was successfully updated.' }
        format.json { render :show, status: :ok, location: @frontpage }
      else
        format.html { render :edit }
        format.json { render json: @frontpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frontpages/1
  # DELETE /frontpages/1.json
  def destroy
    @frontpage.destroy
    respond_to do |format|
      format.html { redirect_to frontpages_url, notice: 'Frontpage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frontpage
      @frontpage = Frontpage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frontpage_params
      params.fetch(:frontpage, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frontpages_helper.rb
module FrontpagesHelper
end

app/views/frontpages/_form.html.erb
<%= form_with(model: frontpage, local: true) do |form| %>
  <% if frontpage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(frontpage.errors.count, "error") %> prohibited this frontpage from being saved:</h2>

      <ul>
      <% frontpage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/frontpages/edit.html.erb
<h1>Editing Frontpage</h1>

<%= render 'form', frontpage: @frontpage %>

<%= link_to 'Show', @frontpage %> |
<%= link_to 'Back', frontpages_path %>

app/views/frontpages/index.html.erb
<p id="notice"><%= notice %></p>






<div class="jumbotron">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>

<div class="card" style="width: 18rem;">
  <%= image_tag("Fishing.jpg", class: "img-responsive", id: "navbar-logo") %>
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>





<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @frontpages.each do |frontpage| %>
      <tr>
        <td><%= link_to 'Show', frontpage %></td>
        <td><%= link_to 'Edit', edit_frontpage_path(frontpage) %></td>
        <td><%= link_to 'Destroy', frontpage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Frontpage', new_frontpage_path %>

app/views/frontpages/new.html.erb
<h1>New Frontpage</h1>

<%= render 'form', frontpage: @frontpage %>

<%= link_to 'Back', frontpages_path %>

app/views/frontpages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_frontpage_path(@frontpage) %> |
<%= link_to 'Back', frontpages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IlyaWebSite</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  </head>

  <body>
    <%= yield %>
  </body>
</html>